#!/bin/sh
#
# @name Intel Aero Ready to Fly Drone
#
# @board px4_fmu-v2 exclude
# @board px4_fmu-v3 exclude
# @board px4_fmu-v4 exclude
# @board px4_fmu-v4pro exclude
# @board px4_fmu-v5 exclude
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Beat Kueng <beat@px4.io>
#

sh /etc/init.d/rc.mc_defaults

#
# Load default params for this platform
#
if [ $AUTOCNF = yes ]
then
	# Set all params here, then disable autoconfig

	param set COM_DISARM_LAND 3

	param set EKF2_GPS_POS_X -0.0600
	param set EKF2_GPS_POS_Z -0.1000
	param set EKF2_MIN_OBS_DT 50

	param set EKF2_BARO_GATE 10
	param set EKF2_BARO_NOISE 5
	param set EKF2_ACC_NOISE 0.7

	param set LNDMC_Z_VEL_MAX 2.0000

	
	param set MC_ROLLRATE_P 0.1300
	param set MC_ROLLRATE_I 0.07
	param set MC_ROLLRATE_D 0.0012
	param set MC_ROLLRATE_MAX 360
	
	param set MC_PITCHRATE_P 0.1300
	param set MC_PITCHRATE_I 0.07
	param set MC_PITCHRATE_D 0.0012
	param set MC_PITCHRATE_MAX 360	

	param set MC_YAWRATE_P 0.119999997317790985
	param set MC_YAWRATE_I 0.050000000745058060
	param set MC_YAWRATE_D 0

	param set MC_ROLL_P 4.0000 # 8.0
	param set MC_PITCH_P 3.0000 # 8.0
	param set MC_YAW_P 1.000 # 4.0

	param set MPC_XY_VEL_P 0.1500
	param set MPC_XY_VEL_I 0.0100
	param set MPC_XY_VEL_D 0.0050

	param set MPC_Z_VEL_P 0.8000
	param set MPC_Z_VEL_I 0.1500
	param set MPC_Z_VEL_D 0.0000

	param set MPC_XY_P 0.5000 # 1.5
	param set MPC_Z_P 1.000

	param set MPC_LAND_SPEED 0.7000

	param set MPC_MANTHR_MIN 0.0400
	param set MPC_THR_HOVER 0.5000
	param set MPC_THR_MAX 0.9400
	param set MPC_THR_MIN 0.1000


	param set MPC_XY_CRUISE 1.0000 # 8.0
	
	param set MPC_Z_VEL_MAX_DN 4.0000
	param set MPC_Z_VEL_MAX_UP 5.0000
	

	# TELEM2 config
	param set MAV_1_CONFIG 102
	param set MAV_1_RATE 80000
	param set MAV_1_FORWARD 1
	param set SER_TEL2_BAUD 921600

	param set EKF2_AID_MASK 24
	param set EKF2_HGT_MODE 3
	param set EKF2_EV_DELAY 0
	param set EKF2_EV_POS_X 0.1
	param set EKF2_EV_POS_Y 0
	param set EKF2_EV_POS_Z -0.09
fi

if param compare SYS_HITL 0
then
  tap_esc start -d /dev/ttyS0 -n 4
  usleep 300000

  set OUTPUT_MODE tap_esc
fi

set MIXER quad_x
set USE_IO no

